### ISSUE TITLE
In "README.md", "簡" should be “简”.

### ISSUE THREAD

**Issue by gxuamethyst** [shieldfy/API-Security-Checklist#120]
In "README.md", "簡中版" means simplified chinese version, but "簡" is a traditional chinese character, it should be "简".

**Comment by VincentSit** [comment]
Just make a PR directly.

**Comment by Maikuolan** [comment]
Good catch. :-)

**Comment by Maikuolan** [comment]
In anyone wants to review: https://github.com/shieldfy/API-Security-Checklist/pull/121
