### ISSUE TITLE
Question about "Don't auto-increment IDs. Use UUID instead."

### ISSUE THREAD

**Issue by triforcely** [shieldfy/API-Security-Checklist#122]
This might seriously cripple database performance since you are suggesting a data type ~68 bytes larger than an integer and which indexes are much more expensive to compute.

What is the motivation behind this rule?

**Comment by ppazos** [comment]
IMHO auto-increment (int) ids should be used only internally, when retrieving a resource outside your system's control, like an API, I use a secondary ID that is a UUID. This avoids clients to try to GET /important_resource/$i   for $i = 1..100000

**Comment by triforcely** [comment]
Alright, but what's wrong with allowing users to enumerate the API like that? We still should check if the user has permission to access the given resource if it is supposed to be private. In case it is a public API, we can solve this by rate limiting/throttling - which is already mentioned in this repo. This kind of feels like _security through obscurity_, no?

**Comment by ppazos** [comment]
If that is a feature of your API, that's OK, but that is not the case of every API out there. In general, you don't want to give more information than the minimal required by your clients to work with. That includes your internal identification scheme.

**Comment by netcode** [comment]
Thank you @ppazos for the response. 
@triforcely if you still need further clarification, feel free to re-open the issue. Thanks
