### ISSUE TITLE
"algorithm" in the JWT

### ISSUE THREAD

**Issue by okdt** [shieldfy/API-Security-Checklist#127]
It reads, 
> Don't extract the algorithm from the payload. Force the algorithm in the backend (HS256 or RS256).

Normally, we can find "alg" in the header part, not the payload part of JWT.
Well, what is your point of the risk case?

**Comment by okdt** [comment]
If you mean we should disable the "alg" claim of JWT for [the security concern of "alg"](https://www.chosenplaintext.ca/2015/03/31/jwt-algorithm-confusion.html) , you may replace just "payload" to "header", or we may have to mention about the risk of "alg": "none" case.

**Comment by netcode** [comment]
@okdt , Nice catch.
As you said the correct word is header not payload.

**Comment by okdt** [comment]
I made a simple PR.

**Comment by netcode** [comment]
merged #129 . Thanks a lot.
