### ISSUE TITLE
Please pay attention to this repo again

### ISSUE THREAD

**Issue by hylerrix** [shieldfy/API-Security-Checklist#140]
Hi, thx for ur exciting work! This checklist helped me very much.

But I noticed that this repo has had 9 issues & 9 pull requests([including mine](https://github.com/shieldfy/API-Security-Checklist/pulls)) now, which still waiting for a reply.

So, let's make this repo be fashionable again. 😁

**Comment by Maikuolan** [comment]
Performed a number of merges just today. Down to just two open PRs remaining now. :-)

Anyone interested in doing some reviews? Would be helpful to get a better idea about whether to merge, to not merge, possible changes/improvements/etc.

There are numerous open issues, too; a number of them proposing changes, which we don't currently have PRs for. If anyone's willing to tackle any of those, that could be good, too.
