### ISSUE TITLE
Why 'Do not forget and leave the DEBUG mode on.' ?

### ISSUE THREAD

**Issue by trietphm** [shieldfy/API-Security-Checklist#15]
If I leave DEBUG mode on, my api will generate tons of log

**Comment by michaelpittino** [comment]
I think this sentence means that you should not forget to turn it off. "Do not forget [the debug mode], and leave it on [by forgetting that the debug mode exists].

That would be my understanding of it.

**Comment by Maikuolan** [comment]
Maybe something like "Do not forget to turn the DEBUG mode OFF" might be better, instead (less ambiguous)?

**Comment by netcode** [comment]
I agree , its a little bit ambiguous. 
Fixed in the last commit https://github.com/shieldfy/API-Security-Checklist/commit/0063049f2f41948eaacf9edc82d2f29883c757c4
