### ISSUE TITLE
User own resource id should be avoided ?

### ISSUE THREAD

**Issue by nsteinmetz** [shieldfy/API-Security-Checklist#20]
Hi,

I agree with most rules but I don't understand:

```
User own resource id should be avoided. Use /me/orders instead of /user/654321/orders
```

From my perspective. I would prefer use ` /user/654321/orders` than `/me/orders`. For the latter, at the end, I need to do the lookup in all cases. So I prefer a non ambiguitous uri than "/me/orders". Even if more readable from a human point of view, at a technical one, it can lead to confusion.

So shouldn't it be more 

```
User own resource id should be avoided. Avoid using /me/orders. Better/explicitely use /user/654321/orders instead.
```

Thanks for the list, will be useful !

**Comment by netcode** [comment]
The reason to avoid user own id is to avoid IDOR vulnerability as possible.
I will give you another example to make it clear.
imagine this
POST `/user/654321/add_email` , this will add email to current user.
then at your code you got the id and you must make sure that the id matches the authenticated user.
What if you forget that  security check , and the hacker change the ID in the url ?
What if the hacker see the opportunity and try to flood your app with script to try every id ?

so in general , we recommend to use `/me/add_email` first to force you get the object id from authentication and to be hide as possible from hacker eye.

**Comment by Netizen29** [comment]
Thanks for those explanations.

Sometimes, an admin user should be able to access any user resource.
Do you advocate, in that particular case, using /user/:id/ressource making sure that the current user is the resource owner or an admin? Or is there a less risky solution?

**Comment by nsteinmetz** [comment]
@netcode I see your point indeed ; thanks for the precision but as @Netizen29 said, there are cases where the `/me/:whatever` is not appropriate nor the  panacea. `/me/:whatever` could be indeed the default case for actions on your own ressource and prevent making some things visible and you can "lower" the security checking as you know you will not impact someone else data. 

You can keep the `/user/:id/ressource` with stronger checkings for admin tasks.

**Comment by guest20** [comment]
Security is based on the most common case, and most users aren't admin. There are also a bunch of things that admin shouldn't be doing but the user herself can... adding ssh keys, setting up 2FA, setting password, setting the name of their first pet, their contact details, viewing PII, or the credit card last-four  etc.

Mostly you don't want your admin user looking at the same view of a user as the user himself. Public profile, sure, but they definitely shouldn't have the same "edit me" form as the actual user.

(Some might even suggest that it's worth having your "back office" functionality in a better protected app that runs elsewhere.)
