### ISSUE TITLE
PUT mentioned, but PATCH is probably a better choice

### ISSUE THREAD

**Issue by geertjanvdk** [shieldfy/API-Security-Checklist#26]
The HTTP method PATCH might not be in the standard yet, but it's widely used. It would be good to mention it, as it makes partial updates "possible".

Reference: https://tools.ietf.org/html/rfc5789

**Comment by jaylinski** [comment]
JSON API also recommends PATCH.

Reference: http://jsonapi.org/faq/#wheres-put

**Comment by netcode** [comment]
Thanks for mention PATCH , fixed in the last commit https://github.com/shieldfy/API-Security-Checklist/commit/b1df247d8a5bf150df3a291a7757d403957b034a
