### ISSUE TITLE
 Don't reinvent the wheel in Authentication, token generating, password storing use the standards.

### ISSUE THREAD

**Issue by XYF001** [shieldfy/API-Security-Checklist#32]
So, for the topic, which standards for  Authentication, token generating, password storing can be used? Can offer some sample implement projects?

**Comment by netcode** [comment]
There is a lot of standards and best practice , some are mentioned here in the list like `JWT` , `OAUTH` for Authentication/Autherization and some not like password storing for example the industry standard now is `BCrypt`.
you can search for Token Generating  & Password Storing and you will got a lot of suggessions and recommenditions.
I hope i helped, Ping me if you want more clarifications.
