### ISSUE TITLE
Add a CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by Maikuolan** [shieldfy/API-Security-Checklist#34]
*See: https://github.com/blog/1184-contributing-guidelines*

Due to that this repository is currently trending very successfully, the number and frequency of pull requests to the repository, issues created, discussions, etc, I think adding some formal procedures or guidelines to the repository might be a good idea, to avoid possible future problems, unwanted pull requests (so far, all pull requests look pretty good, but there has been 17 of them already, and the repository is only 3 days old, and so, I think, there's a strong chance of merge conflicts, bad/unwanted pull requests and similar such things occurring at some point in the future). 16 issues created thus far in that 3 days, all legit/good, except for one, which looks a bit spammy (#19); Not sure if formal procedures or guidelines would help at all in that regard, but in any case, it couldn't hurt. Anyhow, figured it might be worth suggesting this. :-)

**Comment by netcode** [comment]
That's a very good suggestion.

**Comment by netcode** [comment]
Added a draft for th contributing , can you review and see if it enough or need improvements.
https://github.com/shieldfy/API-Security-Checklist/blob/master/CONTRIBUTING.md

**Comment by Maikuolan** [comment]
*Resolved + closing.*
