### ISSUE TITLE
Suggestion: add version information in base file and translation file

### ISSUE THREAD

**Issue by deforder** [shieldfy/API-Security-Checklist#49]
This will let translation file easily to spot if it is outdated.

I suggest using this format for version control (V.MAJOR.MINOR.REVISION)
MAJOR = new standard / concept
MINOR = add more checklist
REVISION = correct some typo

for example,
Base file(V1.1.2)  
Translation file1(V1.1.1) (Outdated by 0.0.1 version but can be ignored)
Translation file2(V1.1.2) (up to date)
Translation file3(V1.0.1) (Outdated)

Info about version might include in their respective files (let translators handle by themselves), base file or centralize file. 

You might as well consider about the changelog. (not necessary though)

**Comment by netcode** [comment]
Till now the repo is highly changing due to the number of pull request and its only 1 week old, so it will help after just a while to make the list more stable and name it V1.0.0.
and yes semver will organize it all, Thanks.
