### ISSUE TITLE
Translation ideas.

### ISSUE THREAD

**Issue by Maikuolan** [shieldfy/API-Security-Checklist#59]
*Source: [Languages used on the Internet](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet) -> [Content languages for websites](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet#Content_languages_for_websites) (2017.07.16).*

*Note: Source does not distinguish between dialect variants, regional L10N, etc (for example, with Chinese, I would __assume__ that the statistics includes both simplified and traditional writing variants, or with Portuguese, including both Portugal and Brazil variants alike).*

*For the purpose of this issue, I'm only listing the top 10 languages mentioned by the source page (there are 38 mentioned by the source list in total, plus a secondary list on the source page; because this issue is only intended to float some general ideas and doesn't concern any concrete goals or plans, being excessive isn't necessary).*

Rank | Language | Percentage | Translation Coverage
---|---|---|---
1 | English | 51.6% | Original document language.
2 | Russian | 6.6% | Completed (thanks @tsybenko).
3 | Japanese | 5.6% | <strike>In progress</strike> Completed (thanks @arinco and @iogi).
4 | German | 5.6% | <strike>__Not translated.__</strike> Completed (thanks @kloener).
5 | Spanish | 5.1% | <strike>__Not translated.__</strike> Completed (thanks @marc-gr).
6 | French | 4.1% | Completed (thanks @flibustier and @Sinequanonh).
7 | Portuguese | 2.6% | Completed (thanks @marcossffilho).
8 | Italian | 2.3% | <strike>__Not translated.__</strike> Completed (thanks @matteocrippa).
9 | Chinese | 2.0% | Completed (thanks @GrayLand119 and @j-gao).
10 | Polish | 1.7% | <strike>__Not translated.__</strike> Completed (thanks @pilotpirxie).

The purpose of this issue is to suggest possible targets for future language translations, for anyone that might be interested in introducing new translations to the repository. This repository (at this time, currently) is being watched by 205 GitHub users and has 422 forks, and so, maybe this might be useful for someone looking for possible target languages. The logic/rationale here is to hopefully encourage translation of the repository to those languages perceived as being most widely used on the internet (and thus, within the realm of the relevant scope of this repository). *Using alternative sources may yield very different results.*

Based on the above-mentioned information, these could be good possible target languages for translation at this time:

1. <strike>German.</strike> *(translation added 2017.07.20).*
2. <strike>Spanish.</strike> *(translation added 2017.07.17).*
3. <strike>Italian.</strike> *(translation added 2017.07.18).*
4. <strike>Polish.</strike> *(translation added 2017.11.21).*

*Also worth mentioning that because this repository is very young and is still a living document, the possibility of data between translations becoming out-of-sync is quite high. There should be no urgency here.*

**Comment by matteocrippa** [comment]
@Maikuolan just made a PR for `italian`

**Comment by Maikuolan** [comment]
Awesome! Cheers. :-)

**Comment by pilotpirxie** [comment]
@Maikuolan hey, I create PL translation :) 
https://github.com/shieldfy/API-Security-Checklist/pull/95

**Comment by Maikuolan** [comment]
Awesome! Thanks for the help, @pilotpirxie. :+1: 😊

**Comment by Maikuolan** [comment]
*Of course, continued translations are always welcome, but due to that all the translations specifically suggested by this issue have now been completed as of this most recent PR, thus meaning there aren't any more "to-do" items here, I'll mark this issue as closed,*
