### ISSUE TITLE
Japanese translations.

### ISSUE THREAD

**Issue by Maikuolan** [shieldfy/API-Security-Checklist#79]
We now have two Japanese translations for the checklist, `README-ja.md` and `README-jp.md` (just one should be enough, I think).

In terms of the language codes used, `README-ja.md` is more accurate (`jp` is the correct country code for Japan, but `ja` is the correct language code for the Japanese language). However, in terms of the actual translated content, I don't know which of the two would be better, seeing as my understanding of Japanese is very limited.

Perhaps someone who is good with the Japanese language could take a look at the two and send a PR to merge them (from the two files, copy whichever translations are the best, into one single file; delete the remainder)?

Maybe this is something that @arinco or @iogi could take a look at?

Cheers. :+1:

**Comment by donchan922** [comment]
Hi, I'm Japanese.
I merged `README-ja.md` and `README-jp.md`.
Please merge PR if there is no problem☺️

**Comment by Maikuolan** [comment]
Looks good to me; I'll merge it now. Thanks for the help. :+1: 😊
